### ISSUE TITLE
Using the plugin with the Atlas MongoDB Service

### ISSUE THREAD

**Issue by neilor-mendes** [haohanyang/mongodb-datasource#12]
Hello all,

Is it possible to use this plugin to connect to the Atlas MongoDB? I'm trying to use it but for some reason it is falling to connect to the address which is coin-collector.zwqpm.mongodb.net:27017. 

```The error states: server selection error: context deadline exceeded, current topology: { Type: Unknown, Servers: [{ Addr: coin-collector.zwqpm.mongodb.net:3333, Type: Unknown, Last error: dial tcp: lookup coin-collector.zwqpm.mongodb.net on 10.0.2.3:53: no such host }, ] }```

I'm able to connect to different clients like the MongoDB Compass

![image](https://github.com/user-attachments/assets/ba7f1e56-80f0-4436-8d3a-a4cdd3494fcb)

**Comment by haohanyang** [comment]
The log shows you connected to port "3333" instead of "27017". Maybe try port 27017?

**Comment by haohanyang** [comment]
Hi @neilor-mendes . Please check the latest build which should fix your issue

**Comment by neilor-mendes** [comment]
Hello @haohanyang I'm gonna try the latest version and let you know. Thanks.

**Comment by neilor-mendes** [comment]
@haohanyang Found a different issue now, not sure if you want to use this one here to tackle it or if you want me to open a new one but basically when I'm starting the container using the statement below

```
docker run -d -p 3000:3000 --restart=unless-stopped --volume grafana-storage:/var/lib/grafana -e GF_INSTALL_PLUGINS="https://github.com/haohanyang/mongodb-datasource/archive/refs/heads/master.zip;haohanyang-mongodb-datasource" -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=haohanyang-mongodb-datasource" -e "GF_SECURITY_ADMIN_PASSWORD=grafana" --name=grafana grafana/grafana-oss
```

The following error is happening:

```
❯ docker logs grafana
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
Error: ✗ failed to convert to plugin DTO: could not find plugin.json or dist/plugin.json in /var/lib/grafana/plugins/haohanyang-mongodb-datasource
```

**Comment by neilor-mendes** [comment]
@haohanyang the error is different now but seems it is almost there:

```
connection() error occurred during connection handshake: auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AtlasError) bad auth : authentication failed
```

![image](https://github.com/user-attachments/assets/fe351e2c-1b46-415f-b67f-2b6e3fa8ae45)

**Comment by haohanyang** [comment]
Is this related?
https://stackoverflow.com/questions/68927857/mongoexport-auth-error-using-mechanism-scram-sha-1

Maybe try adding “authenticationDatabase=admin” or “authSource=admin” to
“Connection parameter”

**Comment by neilor-mendes** [comment]
@haohanyang never mind bud, there was a typo in my username/password. It is working properly, I was able to connect. I'm sorry for that. 

![image](https://github.com/user-attachments/assets/ba1be2f7-01a1-4c79-b2af-f4664fa2058e)


I'm closing the issue and thanks again for your quick fix!
