### ISSUE TITLE
[FR] Support grafana alerting

### ISSUE THREAD

**Issue by Nobodyno-boop** [haohanyang/mongodb-datasource#15]
Hello, i hope your doing great!

For my purpose i need the alert query by grafana, are open to support this feature ? (https://grafana.com/developers/plugin-tools/tutorials/build-a-data-source-backend-plugin#enable-grafana-alerting) I'd be happy to help you with this feature.

Best regards :D

**Comment by haohanyang** [comment]
Sure! It's a big missing from v0.1.0 release. Feel free to craft it.

**Comment by Nobodyno-boop** [comment]
Its a bit ridiculus, just a `"alerting": true,` in the `plugin.json`, you can enable if you want without any change in the code. But maybe we need some review.

Will actually test it in stagging on a project in few days and hope we not gonna need some some change.

However, it might be interesting to activate the query concurrently ? 
https://grafana.com/developers/plugin-tools/tutorials/build-a-data-source-backend-plugin#run-multiple-queries-concurrently

**Comment by haohanyangdev** [comment]
Could be also interesting to add Query Variable as it's related to https://github.com/haohanyang/mongodb-datasource/issues/16

https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-support-for-variables#add-support-for-query-variables-to-your-data-source

**Comment by haohanyang** [comment]
Any new update on this proposal? @Nobodyno-boop

**Comment by fonzi** [comment]
I saw that @haohanyang enabled in the latest commit to master. Appears that I can add the Mongo Datasource. 

Still testing...

![image](https://github.com/user-attachments/assets/2eef5f0b-06ed-4fd9-b230-538a46d8c21b)

**Comment by fonzi** [comment]
Following up, appears that the latest master push works with alerts. 

![image](https://github.com/user-attachments/assets/cdc9f703-ddd5-44cd-985b-9d2798299eb7)

**Comment by haohanyang** [comment]
This has been now released in the latest version
