### ISSUE TITLE
Dashboard -> Variables

### ISSUE THREAD

**Issue by neilor-mendes** [haohanyang/mongodb-datasource#16]
@haohanyang is it also possible to add the feature to support [dashboard variables](https://grafana.com/docs/grafana/latest/dashboards/variables/)? I tried it but seems the plugins is missing some components to make it work.

Variables is very useful to create more interactive and dynamic dashboards

![image](https://github.com/user-attachments/assets/362d600d-03ef-4820-ab13-0e089a7a4972)

Found this link, maybe it can help: https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-support-for-variables

**Comment by haohanyang** [comment]
The plugin doesn's support Query Variable but it supports , for example, custom variables which you enter manually from the dashboard. If that is want you want?

<img width="486" alt="image" src="https://github.com/user-attachments/assets/7cbdf60d-7038-464f-a249-dc9792fd1af4">

**Comment by neilor-mendes** [comment]
Are you planning to develop the Query Variable ?

Actually I'd like to dynamically, based on a query, build the list of possible values available for the filter instead of the custom variable. My use case we has a lot of different values and would be nice to count on it.

Here is an example but for influx db https://youtu.be/6jYKn5ULJX0?t=368

**Comment by haohanyang** [comment]
I didn't read through the "Query Variables" in the first time when I implemented the plugin. But it looks like a power feature. Will plan it for future release.

**Comment by neilor-mendes** [comment]
Do you have an ETA for it? Just to understand how I can overcome this need now.

**Comment by haohanyang** [comment]
I anticipate the first iteration could happen in this week

**Comment by haohanyang** [comment]
Added https://github.com/haohanyang/mongodb-datasource/pull/17 to fix this

Package: https://github.com/haohanyang/mongodb-datasource/actions/runs/11371029920

**Comment by haohanyang** [comment]
It's ready for test now. Necessary changes can be done in this PR

**Comment by neilor-mendes** [comment]
am I missing anything here? I still can't see the textbox to write the query after the plugin get upgraded.

![image](https://github.com/user-attachments/assets/41a15ea4-169d-410a-baf2-14487bad8c04)

**Comment by haohanyang** [comment]
Did you download the correct package?

https://github.com/haohanyang/mongodb-datasource/actions/runs/11371029920

**Comment by neilor-mendes** [comment]
Let me test again @haohanyang

**Comment by neilor-mendes** [comment]
@haohanyang I downloaded it again and didn't work. What I can check to make sure I'm using the right package?

`-rw-r--r-- 1 admin admin     2498 Oct 16 17:47 README.md
-rw-r--r-- 1 admin admin      850 Oct 16 17:47 plugin.json
-rw-r--r-- 1 admin admin    60508 Oct 16 17:47 module.js.map
-rw-r--r-- 1 admin admin    23657 Oct 16 17:47 module.js
-rw-r--r-- 1 admin admin    11356 Oct 16 17:47 LICENSE
-rw-r--r-- 1 admin admin       53 Oct 16 17:47 CHANGELOG.md
-rwxr-xr-x 1 admin admin     1044 Oct 16 17:49 go_plugin_build_manifest
-rwxr-xr-x 1 admin admin 26951680 Oct 16 17:50 gpx_mongodb_datasource_linux_amd64
-rwxr-xr-x 1 admin admin 27695104 Oct 16 17:52 gpx_mongodb_datasource_windows_amd64.exe
-rwxr-xr-x 1 admin admin 25886720 Oct 16 17:52 gpx_mongodb_datasource_linux_arm64
-rwxr-xr-x 1 admin admin 30210304 Oct 16 17:52 gpx_mongodb_datasource_darwin_amd64
-rwxr-xr-x 1 admin admin 25690112 Oct 16 17:52 gpx_mongodb_datasource_linux_arm
-rwxr-xr-x 1 admin admin 29886530 Oct 16 17:52 gpx_mongodb_datasource_darwin_arm64
drwxr-xr-x 2 admin admin     4096 Oct 17 14:49 img/
drwxr-xr-x 3 admin admin     4096 Oct 17 14:49 ./
drwxr-xr-x 9 admin admin     4096 Oct 17 15:06 ../
`

**Comment by haohanyang** [comment]
I updated the mongo version to 0.1.1 so you can see it here 
<img width="554" alt="image" src="https://github.com/user-attachments/assets/2fabfe77-5a89-49bf-afb7-bd910ba97b09">

https://github.com/haohanyang/mongodb-datasource/actions/runs/11401370940/job/31724114683

**Comment by neilor-mendes** [comment]
@haohanyang Now I was able to write the query but seems there is something still not right. On the preview of values down below we are supposed to see the list of values coming from the query not the key name and those values will be used as variable values.


![image](https://github.com/user-attachments/assets/e85e1fe1-c37e-409e-8de6-d8639bec155f)

**Comment by haohanyang** [comment]
I updated the text name so you can view the value: `<field_name>:<values>`
If the array has only 1 element, the value is its element. Otherwise the value is an array that can be formatted according to Grafana's syntax

**Comment by neilor-mendes** [comment]
@haohanyang Gonna test it and let you know!

**Comment by neilor-mendes** [comment]
@haohanyang can we reopen this? I'm just testing it know and seems it is not working as expected yet but you are close.

Se below that it is returnin a object and not only a list of values 
![image](https://github.com/user-attachments/assets/65a67af3-ec0b-440e-aaf3-a1e45bcdfcd1)

**Comment by haohanyang** [comment]
This is indeed an array, want you see is just a `pretty-print`. See https://github.com/haohanyang/mongodb-datasource/blob/e01a63eed95c3053a9d8a725389cebdf8d454b8b/src/utils.ts#L119

**Comment by neilor-mendes** [comment]
@haohanyang ,

Sorry to bother you again but take a look on what is happening.

![image](https://github.com/user-attachments/assets/5d3adab9-2025-4b0a-97ff-a53f7e554fd0)

**Comment by haohanyang** [comment]
Do you want to expand this chipid variable and show 6339425, …, those all
chip ids in the dropdown?

**Comment by neilor-mendes** [comment]
Exactly, each id should be a value in the drop-down

Em seg., 2 de dez. de 2024, 07:27, Haohan Yang ***@***.***>
escreveu:

**Comment by haohanyang** [comment]
Makes sense. I will make a PR to fix this

**Comment by haohanyang** [comment]
@neilor-mendes please check https://github.com/haohanyang/mongodb-datasource/pull/28.

**Comment by neilor-mendes** [comment]
Seems it is working properly now. Did you have a chance to test also with
the "Multiple Selection" checkbox checked?

Em qua., 4 de dez. de 2024, 20:35, Haohan Yang ***@***.***>
escreveu:

**Comment by neilor-mendes** [comment]
I was taking about this Multi-Value option instead

Em qua., 4 de dez. de 2024, 20:35, Haohan Yang ***@***.***>
escreveu:

**Comment by haohanyang** [comment]
Multi-value is supported 
<img width="309" alt="image" src="https://github.com/user-attachments/assets/7291dcf1-7a40-4ffb-9183-8acd4b1cce92">

**Comment by neilor-mendes** [comment]
Thanks a lot! So, how can I download this fix?

Em qui., 5 de dez. de 2024, 13:57, Haohan Yang ***@***.***>
escreveu:

**Comment by haohanyang** [comment]
Download from the latest release v0.2.0

Neilor Mendes ***@***.***>于2024年12月7日 周六下午12:34写道：

**Comment by haohanyang** [comment]
You should project “value”: “$chipid”

**Comment by neilor-mendes** [comment]
Same...

MongoDB:
![image](https://github.com/user-attachments/assets/a710d817-6dc7-4e0e-b999-bf21296b3c37)

Grafana:
![image](https://github.com/user-attachments/assets/84464709-87f7-4aa9-bfec-a3ac191fd844)

**Comment by haohanyang** [comment]
Did you click “Query” button?
