### ISSUE TITLE
MongoDB Plugin Returns Array Data as Object Format Instead of Standard JSON Array

### ISSUE THREAD

**Issue by jeanfliu** [haohanyang/mongodb-datasource#22]
Hello,

I'm encountering an issue with the MongoDB plugin. When I run an aggregation query in Grafana, array data is returned in an object format rather than as a standard JSON array. Here’s an example:

* Expected Output (e.g., from MongoDB in Robot 3T):
```
["a", "b"]
```
or
```
[1, 2, 3, 4]
```

* Actual Output (from this plugin in Grafana):
```
{ "0": "a", "1": "b" } 
```
or
```
{
    "0": { "$numberDouble": "1.0" },
    "1": { "$numberDouble": "2.0" },
    "2": { "$numberDouble": "3.0" },
    "3": { "$numberDouble": "4.0" }
}
```
![image](https://github.com/user-attachments/assets/b104540b-5377-48cc-9b86-4d1e831cbda7)

### Steps to Reproduce:
1. Insert sample data in MongoDB:
```
db.demoColl.insertMany([
    { "name": "series_1", "datas": ["a", "b"] },
    { "name": "series_2", "datas": [1, 2, 3, 4] }
])
```
2. Execute the following aggregation query in Grafana:
```
db.demoColl.aggregate([{ "$project": { "_id": 0 } }])
```

### Environment:
* Grafana version: v11.1.0
* MongoDB plugin version: v0.1.1

The plugin currently returns array data in an object format, with each array element indexed as a key-value pair. Numeric values are wrapped in `$numberDouble`, which complicates direct usage within Grafana.

If the data source could return array data in a standard JSON array format, it could improve consistency and make data handling easier within Grafana.

Thanks for your work on this! Looking forward to your thoughts!

**Comment by haohanyang** [comment]
Good catch. I just realized a better way to unmarshall raw values
```go
var a json.RawMessage
bson.UnmarshalValue(bson.TypeArray, rawValue.Value, &a)
```
or
```go
var a json.RawMessage
bson.UnmarshalValue(bson.TypeEmbeddedDocument, rawValue.Value, &a)
```

I will soon fix it

**Comment by haohanyang** [comment]
@jeanfliu I have a PR that should address this issue.

**Comment by haohanyang** [comment]
@jeanfliu Reopen if issue still exists
