### ISSUE TITLE
Failed to query: (FailedToParse) unrecognized field 'apiVersion'

### ISSUE THREAD

**Issue by kou9** [haohanyang/mongodb-datasource#3]
Hi,

I'm happy to have found this plugin which seems to solve the angular problem of the plugin this one is based on (https://github.com/JamesOsgood/mongodb-grafana/issues/143). So thank you very much for that!

I am running into an issue which could be related to the fact that I am using an older mongodb version (4.4.18, I cannot upgrade for HW reasons). Whichever query I try I always get the error `Failed to query: (FailedToParse) unrecognized field 'apiVersion'`:

![image](https://github.com/user-attachments/assets/ae177d39-4cae-450b-ab0a-09744235e434)

Is it because the plugin is sending an apiVersion field to mongo? Is there a way to not send this field? I'm also trying to find a solution on the mongo side but no luck so far. I am running Grafana 10.4.0.

Thank you again!

**Comment by haohanyang** [comment]
Hi, Thank you for your report

It is possible to remove version info by removing ‘
SetServerAPIOptions(serverAPI)’ at
https://github.com/haohanyang/mongodb-datasource/blob/master/pkg/plugin/datasource.go#L57

 I may soon remove this info to support older versions of MongoDB


Haohan Yang

**Comment by kou9** [comment]
Ah ok indeed, this should do the trick. I need to recompile the plugin myself then (I followed your doc and just downloaded the build with artifcats). Thank you for the fast response!

**Comment by haohanyang** [comment]
Hi, I have merged the PR to remove the server info. You can now download the build directly from GitHub CI.

**Comment by kou9** [comment]
@haohanyang Thank you. It did the trick! I confirm that without the SetServerAPIOptions(serverAPI) line, the query now works as expected and doesn't throw any exception anymore.
