### ISSUE TITLE
Default query should not be an empty array

### ISSUE THREAD

**Issue by haohanyangdev** [haohanyang/mongodb-datasource#6]
The default query is `[]` which could crush the server if the database is very big. I suggest add `$limit` to default query, for example,

```
[
{
 "$limit": 10
}
]
```

**Comment by revir** [comment]
how about
```
[
{ 
  "$match": {} 
},
{
 "$limit": 10
}
]
```

**Comment by haohanyangdev** [comment]
There is no need to add `{ 
  "$match": {} 
}`
