### ISSUE TITLE
Question: Javascript aggregate with small js query

### ISSUE THREAD

**Issue by Nobodyno-boop** [haohanyang/mongodb-datasource#7]
Problem: 
I have a dashboard variable and the aggregare query will depend on it.

Exemple why i was trying to do:

```js
const _user= String($_user) || "";


db.collection("lead").aggregate([
    {
      "$match": {
        "createdAt": {
            "$gt": {
                "$date": {
                    "$numberLong": "$__from"
                }
            },
            "$lt": {
                "$date": {
                    "$numberLong": "$__to"
                }
            }
        },
        ...(_user? { "username": _user} : {})
      }
    },
    {
      "$count": "value"
    }
  ]);
  ```
  
  But i figure it out your just match with a regex so its the same JSON query.
  
  Maybe could be "more extentable" to implement a simple JS function export the aggregate json?

example:
```js
// use a function named aggregate to return the aggregate json
export default function aggregate() {
    // custom logic
    // return aggregate json
    return [
        {}
    ]
}
```

Could be done in isolate function to avoid problem like [vm2](https://www.npmjs.com/package/vm2)  or isolate-vm(vm2 if you wanna passe some query).

I feel stuck without this "logic" to match my filter on my dashboard.

Are you open to put this "feature" with a PR ?

**Comment by haohanyang** [comment]
Sure, PRs are always welcome. 

Initially introducing JS code is for a more convenient migration from an old plugin, and not really for a dynamic "scripting". 

My question is: how to "execute/interpret" this JS code to json?
