### ISSUE TITLE
Using $bucketAuto and $dateBucketCount

### ISSUE THREAD

**Issue by kou9** [haohanyang/mongodb-datasource#9]
Hi,

I could recreate most of my panels that used the old Mongo plugin with this plugin which is fantastic! I am running into a type problem with the use of aggregate queries that use $bucketAuto and $dateBucketCount.

If I create a stage that looks like this, I get an error that the "buckets" subobject should be a number:
```
"$bucketAuto": {
      "groupBy": "$timestamp",
      "buckets": "$dateBucketCount",
      "output": { "sumValue": { "$sum": "$total_fees" } }
    }
```

And if I try to convert the string to a number, the error says that I can't have an object in the "buckets" subobject:
![image](https://github.com/user-attachments/assets/6384724c-2bcf-410f-b8f4-9139357fade8)

It used to work with the old plugin. I wonder if there's a way to implicitly cast $dateBucketCount to an int.

![image](https://github.com/user-attachments/assets/1fac238b-9fb0-4e58-83f7-4eca29b674a5)

**Comment by 3Artem3** [comment]
Can you please give an example of how to create a graph so that it would be visible how many elements were created per minute. I don't understand how to use this plugin, I only get an empty graph.
I would be grateful if someone could tell me how to use it

**Comment by haohanyangdev** [comment]
> Can you please give an example of how to create a graph so that it would be visible how many elements were created per minute. I don't understand how to use this plugin, I only get an empty graph. I would be grateful if someone could tell me how to use it

Say your "element" collection has field `createdTime` (of type `Timestamp`). The query to show created elements per minute is the following

```json
[
  {
    "$match": {
      "createdTime": {
        "$gte": {
          "$date": {
            "$numberLong": "$__from"
          }
        },
        "$lte": {
          "$date": {
            "$numberLong": "$__to"
          }
        }
      }
    }
  },
  {
    "$group": {
      "_id": {
        "$dateToString": {
          "format": "%Y-%m-%dT%H:%M",
          "date": "$createdTime"
        }
      },
      "count": {
        "$count": {}
      }
    }
  },
  {
    "$project": {
      "name": "elements",
      "value": "$count",
      "ts": {
        "$toDate": "$_id"
      },
      "_id": 0
    }
  }
]
```
To show graph, you should select query type "time series" and return `ts`, `count` and `name`(optional, behaves like "legend" in graph) in your mongo query

**Comment by haohanyang** [comment]
> Hi,
> 
> 
> 
> I could recreate most of my panels that used the old Mongo plugin with this plugin which is fantastic! I am running into a type problem with the use of aggregate queries that use $bucketAuto and $dateBucketCount.
> 
> 
> 
> If I create a stage that looks like this, I get an error that the "buckets" subobject should be a number:
> 
> ```
> 
> "$bucketAuto": {
> 
>       "groupBy": "$timestamp",
> 
>       "buckets": "$dateBucketCount",
> 
>       "output": { "sumValue": { "$sum": "$total_fees" } }
> 
>     }
> 
> ```
> 
> 
> 
> And if I try to convert the string to a number, the error says that I can't have an object in the "buckets" subobject:
> 
> ![image](https://github.com/user-attachments/assets/6384724c-2bcf-410f-b8f4-9139357fade8)
> 
> 
> 
> It used to work with the old plugin. I wonder if there's a way to implicitly cast $dateBucketCount to an int.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/1fac238b-9fb0-4e58-83f7-4eca29b674a5)
> 
> 

Is "$dateBucketCount" a template variable in Grafana dashboard? If so you can check formatting rules https://grafana.com/docs/grafana/latest/dashboards/variables/variable-syntax/

**Comment by haohanyang** [comment]
The query editor is just the editor of this plugin. It complains if you enter an invalid json like this (lacking surrounding double quotation marks)

```
"buckets": ${dateBucketCount}

```
When you lose focus on the editor, it automatically queries if the input is a valid json. You can manually query by clicking "Query inspector" and then click "Refresh". Then you can see it refreshes and you can check the query sent to backend(with template variables already replaced) . Since it is actually a valid json after replacing template variables( assuming it is just an integer) you can get the query result successfully.

**Comment by haohanyang** [comment]
FYI, I would consider adding support to "$dateBucketCount" to make it more convenient for old plugin users to migrate

**Comment by haohanyang** [comment]
@kou9 The recent patch has fixed this issue. Please reopen it if you run into any relevant issue again

**Comment by kou9** [comment]
Excellent! Thank you @haohanyang . I can confirm that the patch works and my mongo queries which used $dateBucketCount with the old plugin can be copy-pasted and used as they are with this plugin.
